name: Create Assets

on:
  release:
    types: [published]
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Build the project
      run: |
        touch privgen-dummy
        echo "stack build" >> privgen-dummy
        tar -cavf privgen.tar.gz privgen-dummy
        
    - name: Upload assets
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './privgen.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}
