name: Create Assets

on:
  release:
    types: [published]
    
permissions: read-all|write-all
    
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Build the project
      run: |
        touch privgen-dummy
        echo "staack build" >> privgen-dummy
        tar -cavf privgen.tar.gz privgen-dummy
        
    - name: Tar and strip the binary
      run: |
        export PROGRAM=privgen-exe
        cp `stack exec -- which $PROGRAM` $PROGRAM
        tar -cavf privgen.tar.gz $PROGRAM
        
    - name: Upload assets
      uses: AButler/upload-release-assets@v2.0
      with:
        files: './privgen.tar.gz'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        release-tag: ${{ github.ref }}
